<a href="https://colab.research.google.com/github/ponshivavel/python/blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%pip install numpy

In [2]:
import numpy as np

In [3]:
print(np.__version__)

2.0.2


In [4]:
## 1. Creating arrays

In [5]:
list1=[1,2,3]
print(list1)

[1, 2, 3]


In [6]:
arr_list1 = np.array(list1)
print(arr_list1)

[1 2 3]


In [7]:
print(type(arr_list1))

<class 'numpy.ndarray'>


In [8]:
list1=[1,2,3]
list2=[4,5,6]
list3=[7,8,9]
print(list1,list2,list3)

[1, 2, 3] [4, 5, 6] [7, 8, 9]


In [9]:
arr_list1=np.array(list1)
arr_list2=np.array(list2)
arr_list3=np.array(list3)
print(arr_list1)
print(arr_list2)
print(arr_list3)

[1 2 3]
[4 5 6]
[7 8 9]


In [10]:
list1=[1,2,3]
list2=[4,5,6]
arr_list1_2 = np.array([list1,list2])
print(arr_list1_2)

[[1 2 3]
 [4 5 6]]


In [11]:
list1=[1,2,3]
list2=[4,5,6]
list3=[7,8,9]
arr_list1_3 = np.array([[list1,list2,list3]])
print(arr_list1_3)


[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [12]:
print(arr_list1_3.ndim)

3


In [13]:
# 2.Numpy Array Attributes.

In [14]:
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [15]:
print ("SHAPE",arr1.shape)
print("Size",arr1.size)
print("Data Type",arr1.dtype)
print("n_dim",arr1.ndim)

SHAPE (2, 3)
Size 6
Data Type int64
n_dim 2


In [16]:
arr2=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr2)

print("SHAPE",arr2.shape)
print("SIZE",arr2.size)
print("DATA TYPE",arr2.dtype)
print("n_dim",arr2.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
SHAPE (1, 3, 3)
SIZE 9
DATA TYPE int64
n_dim 3


In [17]:
arr1=np.array([1,2,3])
print(arr1)

print("SHAPE",arr1.shape)
print("SIZE",arr1.size)
print("DATA TYPE",arr1.dtype)
print("n_dim",arr1.ndim)


[1 2 3]
SHAPE (3,)
SIZE 3
DATA TYPE int64
n_dim 1


In [18]:
# 3. Array initialization methods

In [19]:
# Zero Array
zero_arr = np.zeros((2,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
# One Array
One_arr = np.ones((3,3))
print(One_arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [21]:
Full_arr = np.full((2,3),7)
print(Full_arr)

[[7 7 7]
 [7 7 7]]


In [22]:
Full_arr = np.full((3,3),4)
print(Full_arr)


[[4 4 4]
 [4 4 4]
 [4 4 4]]


In [23]:
# Identity Methods/Matrix/3x3/Square Matrix

id_arr = np.eye(3)
print(id_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
# Empty Array
print(np.empty(2))

[4.94065646e-324 6.88361495e-310]


In [25]:
# Evenly Spaced Array
print(np.arange(1,3,1))

[1 2]


In [26]:
print(np.arange(4,8,2))

[4 6]


In [27]:
print(np.arange(4,42,4))

[ 4  8 12 16 20 24 28 32 36 40]


In [28]:
print(np.arange(12,121,12))

[ 12  24  36  48  60  72  84  96 108 120]


In [29]:
# Specific number of equaly (spaced) values b/w arange.
print(np.linspace(1,10,4))

[ 1.  4.  7. 10.]


In [30]:
# Random values array -float
r_arr = np.random.rand(3,2)
print(r_arr)

[[0.21095905 0.00576077]
 [0.29953805 0.86916676]
 [0.84802411 0.37101922]]


In [31]:
# Random Values Araay -int
rint_arr = np.random.randint(8,80,(3,3))
print(rint_arr)

[[28 59 70]
 [21 14 61]
 [26 11 39]]


In [32]:
# 4. array Indexing and slicing

In [33]:
a =np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [34]:
print(a[0])

1


In [35]:
print(a[3])

4


In [36]:
a=np.array([3,5,6,7,3,4,5,6,9,1,2])
print(a)
# Slicing:
# array[start:stop:step]
# stop - index, that is not included in output.

[3 5 6 7 3 4 5 6 9 1 2]


In [37]:
print(a[0:3]) # First 3 elements

[3 5 6]


In [38]:
print(a[-6:]) # Last 3 elements

[4 5 6 9 1 2]


In [39]:
print(a[1:8:2])

[5 7 4 6]
