<a href="https://colab.research.google.com/github/ponshivavel/python/blob/main/Numpy/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
arr2 = np.array([[1,2,3,4],[4,5,6,7]])
print(arr2)

[[1 2 3 4]
 [4 5 6 7]]


In [ ]:
print(arr2[0])

[1 2 3 4]


In [ ]:
print(arr2[0][0])

1


In [ ]:
print(arr2[1][2])

6


In [ ]:
arr3 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(arr3[0])
print(arr3[2])
print(arr3[1])
print(arr3[0][2])
print(arr3[2][2])



[1 2 3]
[7 8 9]
[4 5 6]
3
9


In [ ]:
print(arr3[:,0]) # 1st colomn value
print(arr3[0]) # 1st Row value

[1 4 7]
[1 2 3]


In [ ]:
# 5. Array Reshaping and Flattening

In [ ]:
arr1 = np.array([1,2,3,4])
print(arr1)

[1 2 3 4]


In [ ]:
reshaped = arr1.reshape((4,1))
print(reshaped)

[[1]
 [2]
 [3]
 [4]]


In [ ]:
reshaped2 = arr1.reshape((4,1))
print(reshaped2)

[[1]
 [2]
 [3]
 [4]]


In [ ]:
print(reshaped2.flatten())

[1 2 3 4]


In [ ]:
# 6 Array_Stacking_and_Spliting

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.vstack((a,b))) # vertical stacking - row wise


[[1 2 3]
 [4 5 6]]


In [ ]:
print(np.hstack((a,b))) # Horizontal stacking - colomn wise

[1 2 3 4 5 6]


In [ ]:
c = np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [ ]:
split = np.hsplit(c,3)

for s in split:
    print(s)

[[1]
 [4]]
[[2]
 [5]]
[[3]
 [6]]


In [ ]:
split = np.vsplit(c,2)

for s in split:
    print(s)

[[1 2 3]]
[[4 5 6]]


In [ ]:
# Mathematical Operation on Array

In [ ]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
print(a+10)
print(a-3)
print(a*2)
print(a/1)

[11 12 13]
[-2 -1  0]
[2 4 6]
[1. 2. 3.]


In [ ]:
b = np.array([1,4,9])
print(b)

[1 4 9]


In [ ]:
print(np.square(b))
print(np.sqrt(b))

[ 1 16 81]
[1. 2. 3.]


In [ ]:
a = np.array([[[1,2,3],
               [4,5,6],
               [8,9,7]]])
b = np.array([[[2,3,4],
               [8,7,9],
               [4,5,6]]])
print(a)
print(b)

[[[1 2 3]
  [4 5 6]
  [8 9 7]]]
[[[2 3 4]
  [8 7 9]
  [4 5 6]]]


In [ ]:
print(a+b)
print(a-b)
print(a*b)

[[[ 3  5  7]
  [12 12 15]
  [12 14 13]]]
[[[-1 -1 -1]
  [-4 -2 -3]
  [ 4  4  1]]]
[[[ 2  6 12]
  [32 35 54]
  [32 45 42]]]


In [ ]:
print(a.T)

[[[1]
  [4]
  [8]]

 [[2]
  [5]
  [9]]

 [[3]
  [6]
  [7]]]


In [ ]:
# Statistical Functions

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(np.sum(a))
print(np.mean(a))
print(np.min(a))
print(np.max(a))

21
3.5
1
6


In [ ]:
a = np.array([[[1,2,3],
               [4,5,6],
               [8,9,7]]])
b = np.array([[[2,3,4],
               [8,7,9],
               [4,5,6]]])
print(a)
print(b)

[[[1 2 3]
  [4 5 6]
  [8 9 7]]]
[[[2 3 4]
  [8 7 9]
  [4 5 6]]]


In [ ]:
print(a == b)

[[[False False False]
  [False False False]
  [False False False]]]


In [ ]:
print(np.array_equal(a,b))

False


In [ ]:
# Broadcasting

In [ ]:
b = np.array([[1,4,9],[3,4,5]])
a = np.array([1,4,9])
print(a+b)


[[ 2  8 18]
 [ 4  8 14]]
